name: Makefile VITA

on:
  push:
    branches: [ psvita ]
  pull_request:
    branches: [ psvita ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Register env variables
      run: >
        export VITASDK=/usr/local/vitasdk &&
        export PATH=$VITASDK/bin:$PATH
        
        
    - name: Download vitasdk
      run: >
        git clone https://github.com/vitasdk/vdpm &&
        cd vdpm &&
        ./bootstrap-vitasdk.sh &&
        ./install-all.sh &&
        sudo ./usr/local/vitasdk/bin/vitasdk-update
        
    - name: Install dependencies
      run: >
        sudo apt-get update -y &&
        sudo apt-get install -y libsdl1.2-dev libsdl2-dev
      
    - name: Build
      working-directory: ${{github.workspace}}
      shell: bash
      run: make -f Makefile.vita  vita

